#ifndef _ENUMS_H_
#define _ENUMS_H_

#include "common.h"

enum ITEMS {
    ITEM_NONE = -1,
    ITEM_MUSHROOM = 0,
    ITEM_SKELETON_KEY = 1,
    ITEM_POISON_MUSHROOM = 2,
    ITEM_REVERSE_MUSHROOM = 3,
    ITEM_CELLULAR_SHOPPER = 4,
    ITEM_WARP_BLOCK = 5,
    ITEM_PLUNDER_CHEST = 6,
    ITEM_BOWSER_PHONE = 7,
    ITEM_DUEL_GLOVE = 8,
    ITEM_LUCKY_LAMP = 9,
    ITEM_GOLDEN_MUSHROOM = 10,
    ITEM_BOO_BELL = 11,
    ITEM_BOO_REPELLENT = 12,
    ITEM_BOWSER_SUIT = 13,
    ITEM_MAGIC_LAMP = 14,
    ITEM_KOOPA_KARD = 15,
    ITEM_BARTER_BOX = 16,
    ITEM_LUCKY_CHARM = 17,
    ITEM_WACKY_WATCH = 18,
    ITEMS_END
};

enum MINIGAME_TYPE {
    MINIGAME_4P,
    MINIGAME_1V3,
    MINIGAME_2V2,
    MINIGAME_ITEM,
    MINIGAME_BATTLE,
    MINIGAME_1V1
};

enum CHARACTER_IMAGES {
    CHAR_TOAD = 3,
    CHAR_BABY_BOWSER = 5,
};

#endif //_ENUMS_H_