#include "common.h"

typedef struct OverlayTable {
/* 0x00 */ u8* romStart;
/* 0x04 */ u8* romEnd;
/* 0x08 */ u8* vramStart;
/* 0x0C */ u8* textVramStart;
/* 0x10 */ u8* textVramEnd;
/* 0x14 */ u8* dataVramStart;
/* 0x18 */ u8* dataVramEnd;
/* 0x1C */ u8* bssVramStart;
/* 0x20 */ u8* bssVramEnd;
} OverlayTable; //sizeof 0x24

u8 D_800962F0[] = {0, 0, 0, 0};

OverlayTable _ovltbl[] = {
    {name_00_ROM_START, name_00_ROM_END, name_00_VRAM, name_00_TEXT_START, name_00_TEXT_END, name_00_DATA_START, name_00_RODATA_END, name_00_BSS_START, name_00_BSS_END },
    {name_01_ROM_START, name_01_ROM_END, name_01_VRAM, name_01_TEXT_START, name_01_TEXT_END, name_01_DATA_START, name_01_RODATA_END, name_01_BSS_START, name_01_BSS_END },
    {name_02_ROM_START, name_02_ROM_END, name_02_VRAM, name_02_TEXT_START, name_02_TEXT_END, name_02_DATA_START, name_02_RODATA_END, name_02_BSS_START, name_02_BSS_END },
    {name_03_ROM_START, name_03_ROM_END, name_03_VRAM, name_03_TEXT_START, name_03_TEXT_END, name_03_DATA_START, name_03_RODATA_END, name_03_BSS_START, name_03_BSS_END },
    {name_04_ROM_START, name_04_ROM_END, name_04_VRAM, name_04_TEXT_START, name_04_TEXT_END, name_04_DATA_START, name_04_RODATA_END, name_04_BSS_START, name_04_BSS_END },
    {name_05_ROM_START, name_05_ROM_END, name_05_VRAM, name_05_TEXT_START, name_05_TEXT_END, name_05_DATA_START, name_05_RODATA_END, name_05_BSS_START, name_05_BSS_END },
    {name_06_ROM_START, name_06_ROM_END, name_06_VRAM, name_06_TEXT_START, name_06_TEXT_END, name_06_DATA_START, name_06_RODATA_END, name_06_BSS_START, name_06_BSS_END },
    {name_07_ROM_START, name_07_ROM_END, name_07_VRAM, name_07_TEXT_START, name_07_TEXT_END, name_07_DATA_START, name_07_RODATA_END, name_07_BSS_START, name_07_BSS_END },
    {name_08_ROM_START, name_08_ROM_END, name_08_VRAM, name_08_TEXT_START, name_08_TEXT_END, name_08_DATA_START, name_08_RODATA_END, name_08_BSS_START, name_08_BSS_END },
    {name_09_ROM_START, name_09_ROM_END, name_09_VRAM, name_09_TEXT_START, name_09_TEXT_END, name_09_DATA_START, name_09_RODATA_END, name_09_BSS_START, name_09_BSS_END },
    {name_0A_ROM_START, name_0A_ROM_END, name_0A_VRAM, name_0A_TEXT_START, name_0A_TEXT_END, name_0A_DATA_START, name_0A_RODATA_END, name_0A_BSS_START, name_0A_BSS_END },
    {name_0B_ROM_START, name_0B_ROM_END, name_0B_VRAM, name_0B_TEXT_START, name_0B_TEXT_END, name_0B_DATA_START, name_0B_RODATA_END, name_0B_BSS_START, name_0B_BSS_END },
    {name_0C_ROM_START, name_0C_ROM_END, name_0C_VRAM, name_0C_TEXT_START, name_0C_TEXT_END, name_0C_DATA_START, name_0C_RODATA_END, name_0C_BSS_START, name_0C_BSS_END },
    {name_0D_ROM_START, name_0D_ROM_END, name_0D_VRAM, name_0D_TEXT_START, name_0D_TEXT_END, name_0D_DATA_START, name_0D_RODATA_END, name_0D_BSS_START, name_0D_BSS_END },
    {name_0E_ROM_START, name_0E_ROM_END, name_0E_VRAM, name_0E_TEXT_START, name_0E_TEXT_END, name_0E_DATA_START, name_0E_RODATA_END, name_0E_BSS_START, name_0E_BSS_END },
    {name_0F_ROM_START, name_0F_ROM_END, name_0F_VRAM, name_0F_TEXT_START, name_0F_TEXT_END, name_0F_DATA_START, name_0F_RODATA_END, name_0F_BSS_START, name_0F_BSS_END },
    {name_10_ROM_START, name_10_ROM_END, name_10_VRAM, name_10_TEXT_START, name_10_TEXT_END, name_10_DATA_START, name_10_RODATA_END, name_10_BSS_START, name_10_BSS_END },
    {name_11_ROM_START, name_11_ROM_END, name_11_VRAM, name_11_TEXT_START, name_11_TEXT_END, name_11_DATA_START, name_11_RODATA_END, name_11_BSS_START, name_11_BSS_END },
    {name_12_ROM_START, name_12_ROM_END, name_12_VRAM, name_12_TEXT_START, name_12_TEXT_END, name_12_DATA_START, name_12_RODATA_END, name_12_BSS_START, name_12_BSS_END },
    {name_13_ROM_START, name_13_ROM_END, name_13_VRAM, name_13_TEXT_START, name_13_TEXT_END, name_13_DATA_START, name_13_RODATA_END, name_13_BSS_START, name_13_BSS_END },
    {name_14_ROM_START, name_14_ROM_END, name_14_VRAM, name_14_TEXT_START, name_14_TEXT_END, name_14_DATA_START, name_14_RODATA_END, name_14_BSS_START, name_14_BSS_END },
    {name_15_ROM_START, name_15_ROM_END, name_15_VRAM, name_15_TEXT_START, name_15_TEXT_END, name_15_DATA_START, name_15_RODATA_END, name_15_BSS_START, name_15_BSS_END },
    {name_16_ROM_START, name_16_ROM_END, name_16_VRAM, name_16_TEXT_START, name_16_TEXT_END, name_16_DATA_START, name_16_RODATA_END, name_16_BSS_START, name_16_BSS_END },
    {name_17_ROM_START, name_17_ROM_END, name_17_VRAM, name_17_TEXT_START, name_17_TEXT_END, name_17_DATA_START, name_17_RODATA_END, name_17_BSS_START, name_17_BSS_END },
    {name_18_ROM_START, name_18_ROM_END, name_18_VRAM, name_18_TEXT_START, name_18_TEXT_END, name_18_DATA_START, name_18_RODATA_END, name_18_BSS_START, name_18_BSS_END },
    {name_19_ROM_START, name_19_ROM_END, name_19_VRAM, name_19_TEXT_START, name_19_TEXT_END, name_19_DATA_START, name_19_RODATA_END, name_19_BSS_START, name_19_BSS_END },
    {name_1A_ROM_START, name_1A_ROM_END, name_1A_VRAM, name_1A_TEXT_START, name_1A_TEXT_END, name_1A_DATA_START, name_1A_RODATA_END, name_1A_BSS_START, name_1A_BSS_END },
    {name_1B_ROM_START, name_1B_ROM_END, name_1B_VRAM, name_1B_TEXT_START, name_1B_TEXT_END, name_1B_DATA_START, name_1B_RODATA_END, name_1B_BSS_START, name_1B_BSS_END },
    {name_1C_ROM_START, name_1C_ROM_END, name_1C_VRAM, name_1C_TEXT_START, name_1C_TEXT_END, name_1C_DATA_START, name_1C_RODATA_END, name_1C_BSS_START, name_1C_BSS_END },
    {name_1D_ROM_START, name_1D_ROM_END, name_1D_VRAM, name_1D_TEXT_START, name_1D_TEXT_END, name_1D_DATA_START, name_1D_RODATA_END, name_1D_BSS_START, name_1D_BSS_END },
    {name_1E_ROM_START, name_1E_ROM_END, name_1E_VRAM, name_1E_TEXT_START, name_1E_TEXT_END, name_1E_DATA_START, name_1E_RODATA_END, name_1E_BSS_START, name_1E_BSS_END },
    {name_1F_ROM_START, name_1F_ROM_END, name_1F_VRAM, name_1F_TEXT_START, name_1F_TEXT_END, name_1F_DATA_START, name_1F_RODATA_END, name_1F_BSS_START, name_1F_BSS_END },
    {name_20_ROM_START, name_20_ROM_END, name_20_VRAM, name_20_TEXT_START, name_20_TEXT_END, name_20_DATA_START, name_20_RODATA_END, name_20_BSS_START, name_20_BSS_END },
    {name_21_ROM_START, name_21_ROM_END, name_21_VRAM, name_21_TEXT_START, name_21_TEXT_END, name_21_DATA_START, name_21_RODATA_END, name_21_BSS_START, name_21_BSS_END },
    {name_22_ROM_START, name_22_ROM_END, name_22_VRAM, name_22_TEXT_START, name_22_TEXT_END, name_22_DATA_START, name_22_RODATA_END, name_22_BSS_START, name_22_BSS_END },
    {name_23_ROM_START, name_23_ROM_END, name_23_VRAM, name_23_TEXT_START, name_23_TEXT_END, name_23_DATA_START, name_23_RODATA_END, name_23_BSS_START, name_23_BSS_END },
    {name_24_ROM_START, name_24_ROM_END, name_24_VRAM, name_24_TEXT_START, name_24_TEXT_END, name_24_DATA_START, name_24_RODATA_END, name_24_BSS_START, name_24_BSS_END },
    {name_25_ROM_START, name_25_ROM_END, name_25_VRAM, name_25_TEXT_START, name_25_TEXT_END, name_25_DATA_START, name_25_RODATA_END, name_25_BSS_START, name_25_BSS_END },
    {name_26_ROM_START, name_26_ROM_END, name_26_VRAM, name_26_TEXT_START, name_26_TEXT_END, name_26_DATA_START, name_26_RODATA_END, name_26_BSS_START, name_26_BSS_END },
    {name_27_ROM_START, name_27_ROM_END, name_27_VRAM, name_27_TEXT_START, name_27_TEXT_END, name_27_DATA_START, name_27_RODATA_END, name_27_BSS_START, name_27_BSS_END },
    {name_28_ROM_START, name_28_ROM_END, name_28_VRAM, name_28_TEXT_START, name_28_TEXT_END, name_28_DATA_START, name_28_RODATA_END, name_28_BSS_START, name_28_BSS_END },
    {name_29_ROM_START, name_29_ROM_END, name_29_VRAM, name_29_TEXT_START, name_29_TEXT_END, name_29_DATA_START, name_29_RODATA_END, name_29_BSS_START, name_29_BSS_END },
    {name_2A_ROM_START, name_2A_ROM_END, name_2A_VRAM, name_2A_TEXT_START, name_2A_TEXT_END, name_2A_DATA_START, name_2A_RODATA_END, name_2A_BSS_START, name_2A_BSS_END },
    {name_2B_ROM_START, name_2B_ROM_END, name_2B_VRAM, name_2B_TEXT_START, name_2B_TEXT_END, name_2B_DATA_START, name_2B_RODATA_END, name_2B_BSS_START, name_2B_BSS_END },
    {name_2C_ROM_START, name_2C_ROM_END, name_2C_VRAM, name_2C_TEXT_START, name_2C_TEXT_END, name_2C_DATA_START, name_2C_RODATA_END, name_2C_BSS_START, name_2C_BSS_END },
    {name_2D_ROM_START, name_2D_ROM_END, name_2D_VRAM, name_2D_TEXT_START, name_2D_TEXT_END, name_2D_DATA_START, name_2D_RODATA_END, name_2D_BSS_START, name_2D_BSS_END },
    {name_2E_ROM_START, name_2E_ROM_END, name_2E_VRAM, name_2E_TEXT_START, name_2E_TEXT_END, name_2E_DATA_START, name_2E_RODATA_END, name_2E_BSS_START, name_2E_BSS_END },
    {name_2F_ROM_START, name_2F_ROM_END, name_2F_VRAM, name_2F_TEXT_START, name_2F_TEXT_END, name_2F_DATA_START, name_2F_RODATA_END, name_2F_BSS_START, name_2F_BSS_END },
    {name_30_ROM_START, name_30_ROM_END, name_30_VRAM, name_30_TEXT_START, name_30_TEXT_END, name_30_DATA_START, name_30_RODATA_END, name_30_BSS_START, name_30_BSS_END },
    {name_31_ROM_START, name_31_ROM_END, name_31_VRAM, name_31_TEXT_START, name_31_TEXT_END, name_31_DATA_START, name_31_RODATA_END, name_31_BSS_START, name_31_BSS_END },
    {name_32_ROM_START, name_32_ROM_END, name_32_VRAM, name_32_TEXT_START, name_32_TEXT_END, name_32_DATA_START, name_32_RODATA_END, name_32_BSS_START, name_32_BSS_END },
    {name_33_ROM_START, name_33_ROM_END, name_33_VRAM, name_33_TEXT_START, name_33_TEXT_END, name_33_DATA_START, name_33_RODATA_END, name_33_BSS_START, name_33_BSS_END },
    {name_34_ROM_START, name_34_ROM_END, name_34_VRAM, name_34_TEXT_START, name_34_TEXT_END, name_34_DATA_START, name_34_RODATA_END, name_34_BSS_START, name_34_BSS_END },
    {name_35_ROM_START, name_35_ROM_END, name_35_VRAM, name_35_TEXT_START, name_35_TEXT_END, name_35_DATA_START, name_35_RODATA_END, name_35_BSS_START, name_35_BSS_END },
    {name_36_ROM_START, name_36_ROM_END, name_36_VRAM, name_36_TEXT_START, name_36_TEXT_END, name_36_DATA_START, name_36_RODATA_END, name_36_BSS_START, name_36_BSS_END },
    {name_37_ROM_START, name_37_ROM_END, name_37_VRAM, name_37_TEXT_START, name_37_TEXT_END, name_37_DATA_START, name_37_RODATA_END, name_37_BSS_START, name_37_BSS_END },
    {name_38_ROM_START, name_38_ROM_END, name_38_VRAM, name_38_TEXT_START, name_38_TEXT_END, name_38_DATA_START, name_38_RODATA_END, name_38_BSS_START, name_38_BSS_END },
    {name_39_ROM_START, name_39_ROM_END, name_39_VRAM, name_39_TEXT_START, name_39_TEXT_END, name_39_DATA_START, name_39_RODATA_END, name_39_BSS_START, name_39_BSS_END },
    {name_3A_ROM_START, name_3A_ROM_END, name_3A_VRAM, name_3A_TEXT_START, name_3A_TEXT_END, name_3A_DATA_START, name_3A_RODATA_END, name_3A_BSS_START, name_3A_BSS_END },
    {name_3B_ROM_START, name_3B_ROM_END, name_3B_VRAM, name_3B_TEXT_START, name_3B_TEXT_END, name_3B_DATA_START, name_3B_RODATA_END, name_3B_BSS_START, name_3B_BSS_END },
    {name_3C_ROM_START, name_3C_ROM_END, name_3C_VRAM, name_3C_TEXT_START, name_3C_TEXT_END, name_3C_DATA_START, name_3C_RODATA_END, name_3C_BSS_START, name_3C_BSS_END },
    {name_3D_ROM_START, name_3D_ROM_END, name_3D_VRAM, name_3D_TEXT_START, name_3D_TEXT_END, name_3D_DATA_START, name_3D_RODATA_END, name_3D_BSS_START, name_3D_BSS_END },
    {name_3E_ROM_START, name_3E_ROM_END, name_3E_VRAM, name_3E_TEXT_START, name_3E_TEXT_END, name_3E_DATA_START, name_3E_RODATA_END, name_3E_BSS_START, name_3E_BSS_END },
    {name_3F_ROM_START, name_3F_ROM_END, name_3F_VRAM, name_3F_TEXT_START, name_3F_TEXT_END, name_3F_DATA_START, name_3F_RODATA_END, name_3F_BSS_START, name_3F_BSS_END },
    {name_40_ROM_START, name_40_ROM_END, name_40_VRAM, name_40_TEXT_START, name_40_TEXT_END, name_40_DATA_START, name_40_RODATA_END, name_40_BSS_START, name_40_BSS_END },
    {name_41_ROM_START, name_41_ROM_END, name_41_VRAM, name_41_TEXT_START, name_41_TEXT_END, name_41_DATA_START, name_41_RODATA_END, name_41_BSS_START, name_41_BSS_END },
    {name_42_ROM_START, name_42_ROM_END, name_42_VRAM, name_42_TEXT_START, name_42_TEXT_END, name_42_DATA_START, name_42_RODATA_END, name_42_BSS_START, name_42_BSS_END },
    {name_43_ROM_START, name_43_ROM_END, name_43_VRAM, name_43_TEXT_START, name_43_TEXT_END, name_43_DATA_START, name_43_RODATA_END, name_43_BSS_START, name_43_BSS_END },
    {name_44_ROM_START, name_44_ROM_END, name_44_VRAM, name_44_TEXT_START, name_44_TEXT_END, name_44_DATA_START, name_44_RODATA_END, name_44_BSS_START, name_44_BSS_END },
    {name_45_ROM_START, name_45_ROM_END, name_45_VRAM, name_45_TEXT_START, name_45_TEXT_END, name_45_DATA_START, name_45_RODATA_END, name_45_BSS_START, name_45_BSS_END },
    {name_46_ROM_START, name_46_ROM_END, name_46_VRAM, name_46_TEXT_START, name_46_TEXT_END, name_46_DATA_START, name_46_RODATA_END, name_46_BSS_START, name_46_BSS_END },
    {name_47_ROM_START, name_47_ROM_END, name_47_VRAM, name_47_TEXT_START, name_47_TEXT_END, name_47_DATA_START, name_47_RODATA_END, name_47_BSS_START, name_47_BSS_END },
    {name_48_ROM_START, name_48_ROM_END, name_48_VRAM, name_48_TEXT_START, name_48_TEXT_END, name_48_DATA_START, name_48_RODATA_END, name_48_BSS_START, name_48_BSS_END },
    {name_49_ROM_START, name_49_ROM_END, name_49_VRAM, name_49_TEXT_START, name_49_TEXT_END, name_49_DATA_START, name_49_RODATA_END, name_49_BSS_START, name_49_BSS_END },
    {name_4A_ROM_START, name_4A_ROM_END, name_4A_VRAM, name_4A_TEXT_START, name_4A_TEXT_END, name_4A_DATA_START, name_4A_RODATA_END, name_4A_BSS_START, name_4A_BSS_END },
    {name_4B_ROM_START, name_4B_ROM_END, name_4B_VRAM, name_4B_TEXT_START, name_4B_TEXT_END, name_4B_DATA_START, name_4B_RODATA_END, name_4B_BSS_START, name_4B_BSS_END },
    {name_4C_ROM_START, name_4C_ROM_END, name_4C_VRAM, name_4C_TEXT_START, name_4C_TEXT_END, name_4C_DATA_START, name_4C_RODATA_END, name_4C_BSS_START, name_4C_BSS_END },
    {name_4D_ROM_START, name_4D_ROM_END, name_4D_VRAM, name_4D_TEXT_START, name_4D_TEXT_END, name_4D_DATA_START, name_4D_RODATA_END, name_4D_BSS_START, name_4D_BSS_END },
    {name_4E_ROM_START, name_4E_ROM_END, name_4E_VRAM, name_4E_TEXT_START, name_4E_TEXT_END, name_4E_DATA_START, name_4E_RODATA_END, name_4E_BSS_START, name_4E_BSS_END },
    {name_4F_ROM_START, name_4F_ROM_END, name_4F_VRAM, name_4F_TEXT_START, name_4F_TEXT_END, name_4F_DATA_START, name_4F_RODATA_END, name_4F_BSS_START, name_4F_BSS_END },
    {name_50_ROM_START, name_50_ROM_END, name_50_VRAM, name_50_TEXT_START, name_50_TEXT_END, name_50_DATA_START, name_50_RODATA_END, name_50_BSS_START, name_50_BSS_END },
    {name_51_ROM_START, name_51_ROM_END, name_51_VRAM, name_51_TEXT_START, name_51_TEXT_END, name_51_DATA_START, name_51_RODATA_END, name_51_BSS_START, name_51_BSS_END },
    {name_52_ROM_START, name_52_ROM_END, name_52_VRAM, name_52_TEXT_START, name_52_TEXT_END, name_52_DATA_START, name_52_RODATA_END, name_52_BSS_START, name_52_BSS_END },
    {name_53_ROM_START, name_53_ROM_END, name_53_VRAM, name_53_TEXT_START, name_53_TEXT_END, name_53_DATA_START, name_53_RODATA_END, name_53_BSS_START, name_53_BSS_END },
    {name_54_ROM_START, name_54_ROM_END, name_54_VRAM, name_54_TEXT_START, name_54_TEXT_END, name_54_DATA_START, name_54_RODATA_END, name_54_BSS_START, name_54_BSS_END },
    {name_55_ROM_START, name_55_ROM_END, name_55_VRAM, name_55_TEXT_START, name_55_TEXT_END, name_55_DATA_START, name_55_RODATA_END, name_55_BSS_START, name_55_BSS_END },
    {name_56_ROM_START, name_56_ROM_END, name_56_VRAM, name_56_TEXT_START, name_56_TEXT_END, name_56_DATA_START, name_56_RODATA_END, name_56_BSS_START, name_56_BSS_END },
    {name_57_ROM_START, name_57_ROM_END, name_57_VRAM, name_57_TEXT_START, name_57_TEXT_END, name_57_DATA_START, name_57_RODATA_END, name_57_BSS_START, name_57_BSS_END },
    {name_58_ROM_START, name_58_ROM_END, name_58_VRAM, name_58_TEXT_START, name_58_TEXT_END, name_58_DATA_START, name_58_RODATA_END, name_58_BSS_START, name_58_BSS_END },
    {name_59_ROM_START, name_59_ROM_END, name_59_VRAM, name_59_TEXT_START, name_59_TEXT_END, name_59_DATA_START, name_59_RODATA_END, name_59_BSS_START, name_59_BSS_END },
    {name_5A_ROM_START, name_5A_ROM_END, name_5A_VRAM, name_5A_TEXT_START, name_5A_TEXT_END, name_5A_DATA_START, name_5A_RODATA_END, name_5A_BSS_START, name_5A_BSS_END },
    {name_5B_ROM_START, name_5B_ROM_END, name_5B_VRAM, name_5B_TEXT_START, name_5B_TEXT_END, name_5B_DATA_START, name_5B_RODATA_END, name_5B_BSS_START, name_5B_BSS_END },
    {name_5C_ROM_START, name_5C_ROM_END, name_5C_VRAM, name_5C_TEXT_START, name_5C_TEXT_END, name_5C_DATA_START, name_5C_RODATA_END, name_5C_BSS_START, name_5C_BSS_END },
    {name_5D_ROM_START, name_5D_ROM_END, name_5D_VRAM, name_5D_TEXT_START, name_5D_TEXT_END, name_5D_DATA_START, name_5D_RODATA_END, name_5D_BSS_START, name_5D_BSS_END },
    {name_5E_ROM_START, name_5E_ROM_END, name_5E_VRAM, name_5E_TEXT_START, name_5E_TEXT_END, name_5E_DATA_START, name_5E_RODATA_END, name_5E_BSS_START, name_5E_BSS_END },
    {name_5F_ROM_START, name_5F_ROM_END, name_5F_VRAM, name_5F_TEXT_START, name_5F_TEXT_END, name_5F_DATA_START, name_5F_RODATA_END, name_5F_BSS_START, name_5F_BSS_END },
    {name_60_ROM_START, name_60_ROM_END, name_60_VRAM, name_60_TEXT_START, name_60_TEXT_END, name_60_DATA_START, name_60_RODATA_END, name_60_BSS_START, name_60_BSS_END },
    {name_61_ROM_START, name_61_ROM_END, name_61_VRAM, name_61_TEXT_START, name_61_TEXT_END, name_61_DATA_START, name_61_RODATA_END, name_61_BSS_START, name_61_BSS_END },
    {name_62_ROM_START, name_62_ROM_END, name_62_VRAM, name_62_TEXT_START, name_62_TEXT_END, name_62_DATA_START, name_62_RODATA_END, name_62_BSS_START, name_62_BSS_END },
    {name_63_ROM_START, name_63_ROM_END, name_63_VRAM, name_63_TEXT_START, name_63_TEXT_END, name_63_DATA_START, name_63_RODATA_END, name_63_BSS_START, name_63_BSS_END },
    {name_64_ROM_START, name_64_ROM_END, name_64_VRAM, name_64_TEXT_START, name_64_TEXT_END, name_64_DATA_START, name_64_RODATA_END, name_64_BSS_START, name_64_BSS_END },
    {name_65_ROM_START, name_65_ROM_END, name_65_VRAM, name_65_TEXT_START, name_65_TEXT_END, name_65_DATA_START, name_65_RODATA_END, name_65_BSS_START, name_65_BSS_END },
    {name_66_ROM_START, name_66_ROM_END, name_66_VRAM, name_66_TEXT_START, name_66_TEXT_END, name_66_DATA_START, name_66_RODATA_END, name_66_BSS_START, name_66_BSS_END },
    {name_67_ROM_START, name_67_ROM_END, name_67_VRAM, name_67_TEXT_START, name_67_TEXT_END, name_67_DATA_START, name_67_RODATA_END, name_67_BSS_START, name_67_BSS_END },
    {name_68_ROM_START, name_68_ROM_END, name_68_VRAM, name_68_TEXT_START, name_68_TEXT_END, name_68_DATA_START, name_68_RODATA_END, name_68_BSS_START, name_68_BSS_END },
    {name_69_ROM_START, name_69_ROM_END, name_69_VRAM, name_69_TEXT_START, name_69_TEXT_END, name_69_DATA_START, name_69_RODATA_END, name_69_BSS_START, name_69_BSS_END },
    {name_6A_ROM_START, name_6A_ROM_END, name_6A_VRAM, name_6A_TEXT_START, name_6A_TEXT_END, name_6A_DATA_START, name_6A_RODATA_END, name_6A_BSS_START, name_6A_BSS_END },
    {name_6B_ROM_START, name_6B_ROM_END, name_6B_VRAM, name_6B_TEXT_START, name_6B_TEXT_END, name_6B_DATA_START, name_6B_RODATA_END, name_6B_BSS_START, name_6B_BSS_END },
    {name_6C_ROM_START, name_6C_ROM_END, name_6C_VRAM, name_6C_TEXT_START, name_6C_TEXT_END, name_6C_DATA_START, name_6C_RODATA_END, name_6C_BSS_START, name_6C_BSS_END },
    {name_6D_ROM_START, name_6D_ROM_END, name_6D_VRAM, name_6D_TEXT_START, name_6D_TEXT_END, name_6D_DATA_START, name_6D_RODATA_END, name_6D_BSS_START, name_6D_BSS_END },
    {name_6E_ROM_START, name_6E_ROM_END, name_6E_VRAM, name_6E_TEXT_START, name_6E_TEXT_END, name_6E_DATA_START, name_6E_RODATA_END, name_6E_BSS_START, name_6E_BSS_END },
    {name_6F_ROM_START, name_6F_ROM_END, name_6F_VRAM, name_6F_TEXT_START, name_6F_TEXT_END, name_6F_DATA_START, name_6F_RODATA_END, name_6F_BSS_START, name_6F_BSS_END },
    {name_70_ROM_START, name_70_ROM_END, name_70_VRAM, name_70_TEXT_START, name_70_TEXT_END, name_70_DATA_START, name_70_RODATA_END, name_70_BSS_START, name_70_BSS_END },
    {name_71_ROM_START, name_71_ROM_END, name_71_VRAM, name_71_TEXT_START, name_71_TEXT_END, name_71_DATA_START, name_71_RODATA_END, name_71_BSS_START, name_71_BSS_END },
    {name_72_ROM_START, name_72_ROM_END, name_72_VRAM, name_72_TEXT_START, name_72_TEXT_END, name_72_DATA_START, name_72_RODATA_END, name_72_BSS_START, name_72_BSS_END },
    {name_73_ROM_START, name_73_ROM_END, name_73_VRAM, name_73_TEXT_START, name_73_TEXT_END, name_73_DATA_START, name_73_RODATA_END, name_73_BSS_START, name_73_BSS_END },
    {name_74_ROM_START, name_74_ROM_END, name_74_VRAM, name_74_TEXT_START, name_74_TEXT_END, name_74_DATA_START, name_74_RODATA_END, name_74_BSS_START, name_74_BSS_END },
    {name_75_ROM_START, name_75_ROM_END, name_75_VRAM, name_75_TEXT_START, name_75_TEXT_END, name_75_DATA_START, name_75_RODATA_END, name_75_BSS_START, name_75_BSS_END },
    {name_76_ROM_START, name_76_ROM_END, name_76_VRAM, name_76_TEXT_START, name_76_TEXT_END, name_76_DATA_START, name_76_RODATA_END, name_76_BSS_START, name_76_BSS_END },
    {name_77_ROM_START, name_77_ROM_END, name_77_VRAM, name_77_TEXT_START, name_77_TEXT_END, name_77_DATA_START, name_77_RODATA_END, name_77_BSS_START, name_77_BSS_END },
    {name_78_ROM_START, name_78_ROM_END, name_78_VRAM, name_78_TEXT_START, name_78_TEXT_END, name_78_DATA_START, name_78_RODATA_END, name_78_BSS_START, name_78_BSS_END },
    {name_79_ROM_START, name_79_ROM_END, name_79_VRAM, name_79_TEXT_START, name_79_TEXT_END, name_79_DATA_START, name_79_RODATA_END, name_79_BSS_START, name_79_BSS_END },
    {name_7A_ROM_START, name_7A_ROM_END, name_7A_VRAM, name_7A_TEXT_START, name_7A_TEXT_END, name_7A_DATA_START, name_7A_RODATA_END, name_7A_BSS_START, name_7A_BSS_END },
    {name_7B_ROM_START, name_7B_ROM_END, name_7B_VRAM, name_7B_TEXT_START, name_7B_TEXT_END, name_7B_DATA_START, name_7B_RODATA_END, name_7B_BSS_START, name_7B_BSS_END },
    {name_7C_ROM_START, name_7C_ROM_END, name_7C_VRAM, name_7C_TEXT_START, name_7C_TEXT_END, name_7C_DATA_START, name_7C_RODATA_END, name_7C_BSS_START, name_7C_BSS_END },
    {name_7D_ROM_START, name_7D_ROM_END, name_7D_VRAM, name_7D_TEXT_START, name_7D_TEXT_END, name_7D_DATA_START, name_7D_RODATA_END, name_7D_BSS_START, name_7D_BSS_END },
    {0x552F50, 0x552F50, 0x801059A0, 0x801059A0, 0x801059A0, 0x801059A0, 0x801059A0, 0x801059A0, 0x801059A0 },
    {name_7F_ROM_START, name_7F_ROM_END, name_7F_VRAM, name_7F_TEXT_START, name_7F_TEXT_END, name_7F_DATA_START, name_7F_RODATA_END, name_7F_BSS_START, name_7F_BSS_END },
};

OverlayTable _modeovltbl[] = {
    {name_80_ROM_START, name_80_ROM_END, name_80_VRAM, name_80_TEXT_START, name_80_TEXT_END, name_80_DATA_START, name_80_RODATA_END, name_80_BSS_START, name_80_BSS_END },
    {name_81_ROM_START, name_81_ROM_END, name_81_VRAM, name_81_TEXT_START, name_81_TEXT_END, name_81_DATA_START, name_81_RODATA_END, name_81_BSS_START, name_81_BSS_END },
    {name_82_ROM_START, name_82_ROM_END, name_82_VRAM, name_82_TEXT_START, name_82_TEXT_END, name_82_DATA_START, name_82_RODATA_END, name_82_BSS_START, name_82_BSS_END },
};